In [1]:
import numpy as np

### 1) Write a program to create a 5 dimensional array with all zeros and ones

In [2]:
a = np.zeros([2,2])
x = np.ones((2,2))
print(a)
print(x)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


### 2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3
   which create a new array of shape (3,10)

In [8]:
x = np.array([np.ones(10), np.zeros(10), np.full(10, 5)])
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


### 3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [20]:
x = np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [30]:
zero_matrix = np.diag(np.arange(10))
print(zero_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


### 5) Write a program to reverse an array (the first element becomes the last).
Given array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [34]:
x = np.arange(12,28)
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [37]:
x[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

### 6) Write a program to create a 2D array with 1 on the border and 0 inside.



In [85]:
border1, border2 = 4, 4
x = np.ones((border1, border2), dtype=int)
x[1:-1,1:-1] = 0
x

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

### 7) Write a program to find common values between two arrays.
Expected Output:


array1: [10 20 40 60]


array2: [10, 30, 40,50]


In [76]:
array1 = np.array([10, 20, 40, 60])
array2 = np.array([10, 30, 40, 50])

common_values = np.intersect1d(array1, array2)
print(common_values)

[10 40]


### 8) Write a program to create an array 2d array and then reshape into 1d array

In [63]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [56]:
y = x.reshape(-2)
y

array([1, 2, 3, 4])